from __future__ import annotations

from uuid import UUID

import structlog
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from sentinel.db.models import Bom, Component, RiskScoreRecord, Scenario
from sentinel.enrichment.merge import merge_enrichment_records

log = structlog.get_logger()


async def generate_risk_report(session: AsyncSession, bom_id: UUID) -> str:
    """Generate a Markdown risk report for a BOM."""
    bom = await session.get(Bom, bom_id)
    if not bom:
        raise ValueError("BOM not found")

    result = await session.execute(
        select(Component)
        .where(Component.bom_id == bom_id)
        .options(
            selectinload(Component.enrichment_records),
            selectinload(Component.risk_scores),
        )
        .order_by(Component.mpn)
    )
    components = result.scalars().all()

    scored = []
    for comp in components:
        latest_risk = max(comp.risk_scores, key=lambda r: r.scored_at, default=None) if comp.risk_scores else None
        latest_enrich = merge_enrichment_records(list(comp.enrichment_records)) if comp.enrichment_records else None
        scored.append((comp, latest_enrich, latest_risk))

    scored.sort(key=lambda x: x[2].composite_score if x[2] else 0, reverse=True)

    critical = sum(1 for _, _, r in scored if r and r.composite_score >= 70)
    high = sum(1 for _, _, r in scored if r and 50 <= r.composite_score < 70)
    medium = sum(1 for _, _, r in scored if r and 30 <= r.composite_score < 50)
    low = sum(1 for _, _, r in scored if r and r.composite_score < 30)
    avg_score = sum(r.composite_score for _, _, r in scored if r) / max(len([s for s in scored if s[2]]), 1)

    lines = [
        f"# SENTINEL Risk Report: {bom.name}",
        "",
        f"**Program**: {bom.program or 'N/A'}",
        f"**Components**: {bom.component_count}",
        f"**Overall Risk Score**: {avg_score:.1f}",
        "",
        "## Risk Summary",
        "",
        f"| Level | Count |",
        f"|-------|-------|",
        f"| Critical (≥70) | {critical} |",
        f"| High (50-69) | {high} |",
        f"| Medium (30-49) | {medium} |",
        f"| Low (<30) | {low} |",
        "",
        "## Top 10 At-Risk Components",
        "",
        "| # | MPN | Manufacturer | Lifecycle | Risk Score | Key Risk Factor | Recommendation |",
        "|---|-----|-------------|-----------|------------|-----------------|----------------|",
    ]

    for idx, (comp, enrich, risk) in enumerate(scored[:10], 1):
        lifecycle = enrich.lifecycle_status if enrich else "Unknown"
        score = f"{risk.composite_score:.1f}" if risk else "N/A"
        top_factor = risk.risk_factors[0]["detail"] if risk and risk.risk_factors else "—"
        rec = (risk.recommendation or "—")[:60] if risk else "—"
        lines.append(f"| {idx} | {comp.mpn} | {comp.manufacturer or '—'} | {lifecycle} | {score} | {top_factor} | {rec} |")

    lines.extend([
        "",
        "## Risk Dimension Breakdown (Top 10)",
        "",
        "| MPN | Lifecycle | Supply | Geographic | Supplier | Regulatory | Composite |",
        "|-----|-----------|--------|------------|----------|------------|-----------|",
    ])

    for comp, _, risk in scored[:10]:
        if risk:
            lines.append(
                f"| {comp.mpn} | {risk.lifecycle_risk:.0f} | {risk.supply_risk:.0f} | "
                f"{risk.geographic_risk:.0f} | {risk.supplier_risk:.0f} | {risk.regulatory_risk:.0f} | "
                f"{risk.composite_score:.1f} |"
            )

    lines.extend(["", "---", f"*Generated by SENTINEL v0.1.0*", ""])
    return "\n".join(lines)


async def generate_scenario_report(session: AsyncSession, scenario_id: UUID) -> str:
    """Generate a Markdown report for a scenario's impact."""
    scenario = await session.get(Scenario, scenario_id)
    if not scenario:
        raise ValueError("Scenario not found")
    if not scenario.results:
        raise ValueError("Scenario has no results")

    results = scenario.results
    summary = results.get("summary", {})
    affected = results.get("affected_components", [])

    lines = [
        f"# SENTINEL Scenario Report: {scenario.name}",
        "",
        f"**Type**: {scenario.scenario_type}",
        f"**Description**: {scenario.description or 'N/A'}",
        f"**Status**: {scenario.status}",
        "",
        "## Impact Summary",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Components Affected | {summary.get('total_components_affected', 0)} |",
        f"| BOMs Affected | {summary.get('boms_affected', 0)} |",
        f"| Avg Risk Delta | +{summary.get('avg_risk_delta', 0):.1f} |",
        f"| Components at Critical | {summary.get('components_at_critical', 0)} |",
        f"| No Alternate Source | {summary.get('components_with_no_alternate_source', 0)} |",
        "",
    ]

    if affected:
        lines.extend([
            "## Affected Components",
            "",
            "| MPN | Manufacturer | Baseline | Scenario | Delta | Recommendation |",
            "|-----|-------------|----------|----------|-------|----------------|",
        ])
        for comp in affected[:20]:
            rec = (comp.get("recommendation") or "—")[:50]
            lines.append(
                f"| {comp['mpn']} | {comp.get('manufacturer', '—')} | "
                f"{comp['baseline_risk']:.1f} | {comp['scenario_risk']:.1f} | "
                f"+{comp['delta']:.1f} | {rec} |"
            )

    lines.extend(["", "---", f"*Generated by SENTINEL v0.1.0*", ""])
    return "\n".join(lines)
